const courses = [
    { course_id: 'ENG 131', credit_hours: 3, prefix: 'ENG', description: 'Freshman English I' },
    { course_id: 'ENG 132', credit_hours: 3, prefix: 'ENG', description: 'Freshman English II' },
    { course_id: 'ENG 230', credit_hours: 3, prefix: 'ENG', description: 'World Literature I' },
    { course_id: 'ENG 231', credit_hours: 3, prefix: 'ENG', description: 'World Literature II' },
    { course_id: 'ENG 235', credit_hours: 3, prefix: 'ENG', description: 'American Literature' },
    { course_id: 'ENG 244', credit_hours: 3, prefix: 'ENG', description: 'African-American Literature' },
    { course_id: 'CHEM 131', credit_hours: 3, prefix: 'CHEM', description: 'Chemistry I' },
    { course_id: 'CHEM 132', credit_hours: 3, prefix: 'CHEM', description: 'Chemistry II' },
    { course_id: 'BIOL 135', credit_hours: 3, prefix: 'BIOL', description: 'Human Anat & Phys I' },
    { course_id: 'BIOL 143', credit_hours: 3, prefix: 'BIOL', description: 'Survey of Life Science' },
    { course_id: 'GEOL 141', credit_hours: 3, prefix: 'GEOL', description: 'Introduction To The Earth' },
    { course_id: 'PHYS 101', credit_hours: 3, prefix: 'PHYS', description: 'Prin of Phys Sci' },
    { course_id: 'PHYS 237', credit_hours: 3, prefix: 'PHYS', description: 'College Physics I' },
    { course_id: 'PHYS 238', credit_hours: 3, prefix: 'PHYS', description: 'College Physics II' },
    { course_id: 'PHYS 251', credit_hours: 3, prefix: 'PHYS', description: 'University Physics I' },
    { course_id: 'MUSI 136', credit_hours: 3, prefix: 'MUSI', description: 'Music Appreciation' },
    { course_id: 'MUSI 239', credit_hours: 3, prefix: 'MUSI', description: 'Fine Arts In Daily Living' },
    { course_id: 'ART 135', credit_hours: 3, prefix: 'ART', description: 'Topics in Contemp Art & Culture' },
    { course_id: 'ART 137', credit_hours: 3, prefix: 'ART', description: 'Intro African Art' },
    { course_id: 'ART 139', credit_hours: 3, prefix: 'ART', description: 'African-American Art & Culture' },
    { course_id: 'THEA 130', credit_hours: 3, prefix: 'THEA', description: 'Introduction to Theatre' },
    { course_id: 'ECON 231', credit_hours: 3, prefix: 'ECON', description: 'Principles Of Economics I' },
    { course_id: 'ECON 232', credit_hours: 3, prefix: 'ECON', description: 'Principles Of Economics II' },
    { course_id: 'HIST 231', credit_hours: 3, prefix: 'HIST', description: 'Soc & Pol Hist US to 1877' },
    { course_id: 'HIST 232', credit_hours: 3, prefix: 'HIST', description: 'Soc & Pol Hist US Since 1877' },
    { course_id: 'HIST 281', credit_hours: 3, prefix: 'HIST', description: 'Intro to African American Hist' },
    { course_id: 'SOC 157', credit_hours: 3, prefix: 'SOC', description: 'Introduction To Sociology' },
    { course_id: 'SOC 158', credit_hours: 3, prefix: 'SOC', description: 'Contemporary Social Issues' },
    { course_id: 'SOC 221', credit_hours: 3, prefix: 'SOC', description: 'Soc Of Human Sexuality' },
    { course_id: 'SOC 238', credit_hours: 3, prefix: 'SOC', description: 'Introduction To Anthropology' },
    { course_id: 'SOC 254', credit_hours: 3, prefix: 'SOC', description: 'Black Perspec In Soc' },
    { course_id: 'GEOG 132', credit_hours: 3, prefix: 'GEOG', description: 'World Regional Geography' },
    { course_id: 'CS 116', credit_hours: 3, prefix: 'CS', description: 'Intro To Compr Science I' },
    { course_id: 'EDCI 210', credit_hours: 3, prefix: 'EDCI', description: 'Ins Tec' },
    { course_id: 'MATH 132', credit_hours: 3, prefix: 'MATH', description: 'Contemporary Mathematics I' },
    { course_id: 'MATH 133', credit_hours: 3, prefix: 'MATH', description: 'College Algebra' },
    { course_id: 'MATH 135', credit_hours: 3, prefix: 'MATH', description: 'Math and Business and Econ I' },
    { course_id: 'MATH 136', credit_hours: 3, prefix: 'MATH', description: 'Precalculus Math' },
    { course_id: 'MIS 204', credit_hours: 3, prefix: 'MIS', description: 'Fundamentals of Info Systems' },
    { course_id: 'POLS 235', credit_hours: 3, prefix: 'POLS', description: 'American Government' },
    { course_id: 'POLS 236', credit_hours: 3, prefix: 'POLS', description: 'Texas Government' },
    { course_id: 'PSY 131', credit_hours: 3, prefix: 'PSY', description: 'General Psychology' },
    { course_id: 'SC 135', credit_hours: 3, prefix: 'SC', description: 'Bus Prof Comm' },
    { course_id: 'SC 136', credit_hours: 3, prefix: 'SC', description: 'Public Address' }
];

export default courses;
