const courses = [
    { course_id: 'ENG 131', credit_hours: 3, prefix: 'ENG' },
    { course_id: 'ENG 132', credit_hours: 3, prefix: 'ENG' },
    { course_id: 'ENG 230', credit_hours: 3, prefix: 'ENG' },
    { course_id: 'ENG 231', credit_hours: 3, prefix: 'ENG' },
    { course_id: 'ENG 235', credit_hours: 3, prefix: 'ENG' },
    { course_id: 'ENG 244', credit_hours: 3, prefix: 'ENG' },
    { course_id: 'CHEM 131', credit_hours: 3, prefix: 'CHEM' },
    { course_id: 'CHEM 132', credit_hours: 3, prefix: 'CHEM' },
    { course_id: 'BIOL 135', credit_hours: 3, prefix: 'BIOL' },
    { course_id: 'BIOL 143', credit_hours: 3, prefix: 'BIOL' },
    { course_id: 'GEOL 141', credit_hours: 3, prefix: 'GEOL' },
    { course_id: 'PHYS 101', credit_hours: 3, prefix: 'PHYS' },
    { course_id: 'PHYS 237', credit_hours: 3, prefix: 'PHYS' },
    { course_id: 'PHYS 238', credit_hours: 3, prefix: 'PHYS' },
    { course_id: 'PHYS 251', credit_hours: 3, prefix: 'PHYS' },
    { course_id: 'MUSI 136', credit_hours: 3, prefix: 'MUSI' },
    { course_id: 'MUSI 239', credit_hours: 3, prefix: 'MUSI' },
    { course_id: 'ART 135', credit_hours: 3, prefix: 'ART' },
    { course_id: 'ART 137', credit_hours: 3, prefix: 'ART' },
    { course_id: 'ART 139', credit_hours: 3, prefix: 'ART' },
    { course_id: 'THEA 130', credit_hours: 3, prefix: 'THEA' },
    { course_id: 'ECON 231', credit_hours: 3, prefix: 'ECON' },
    { course_id: 'ECON 232', credit_hours: 3, prefix: 'ECON' },
    { course_id: 'HIST 231', credit_hours: 3, prefix: 'HIST' },
    { course_id: 'HIST 232', credit_hours: 3, prefix: 'HIST' },
    { course_id: 'HIST 281', credit_hours: 3, prefix: 'HIST' },
    { course_id: 'SOC 157', credit_hours: 3, prefix: 'SOC' },
    { course_id: 'SOC 158', credit_hours: 3, prefix: 'SOC' },
    { course_id: 'SOC 221', credit_hours: 3, prefix: 'SOC' },
    { course_id: 'SOC 238', credit_hours: 3, prefix: 'SOC' },
    { course_id: 'SOC 254', credit_hours: 3, prefix: 'SOC' },
    { course_id: 'GEOG 132', credit_hours: 3, prefix: 'GEOG' },
    { course_id: 'CS 116', credit_hours: 3, prefix: 'CS' },
    { course_id: 'EDCI 210', credit_hours: 3, prefix: 'EDCI' },
    { course_id: 'MATH 132', credit_hours: 3, prefix: 'MATH' },
    { course_id: 'MATH 133', credit_hours: 3, prefix: 'MATH' },
    { course_id: 'MATH 135', credit_hours: 3, prefix: 'MATH' },
    { course_id: 'MATH 136', credit_hours: 3, prefix: 'MATH' },
    { course_id: 'MIS 204', credit_hours: 3, prefix: 'MIS' },
    { course_id: 'POLS 235', credit_hours: 3, prefix: 'POLS' },
    { course_id: 'POLS 236', credit_hours: 3, prefix: 'POLS' },
    { course_id: 'PSY 131', credit_hours: 3, prefix: 'PSY' },
    { course_id: 'SC 135', credit_hours: 3, prefix: 'SC' },
    { course_id: 'SC 136', credit_hours: 3, prefix: 'SC' }
];

export default courses;
