const courses = [
    { courseId: 'ENG 131',creditHours: 3, prefix: 'ENG', description: 'Freshman English I' },
    { courseId: 'ENG 132',creditHours: 3, prefix: 'ENG', description: 'Freshman English II' },
    { courseId: 'ENG 230',creditHours: 3, prefix: 'ENG', description: 'World Literature I' },
    { courseId: 'ENG 231',creditHours: 3, prefix: 'ENG', description: 'World Literature II' },
    { courseId: 'ENG 235',creditHours: 3, prefix: 'ENG', description: 'American Literature' },
    { courseId: 'ENG 244',creditHours: 3, prefix: 'ENG', description: 'African-American Literature' },
    { courseId: 'CHEM 131',creditHours: 3, prefix: 'CHEM', description: 'Chemistry I' },
    { courseId: 'CHEM 132',creditHours: 3, prefix: 'CHEM', description: 'Chemistry II' },
    { courseId: 'BIOL 135',creditHours: 3, prefix: 'BIOL', description: 'Human Anat & Phys I' },
    { courseId: 'BIOL 143',creditHours: 3, prefix: 'BIOL', description: 'Survey of Life Science' },
    { courseId: 'GEOL 141',creditHours: 3, prefix: 'GEOL', description: 'Introduction To The Earth' },
    { courseId: 'PHYS 101',creditHours: 3, prefix: 'PHYS', description: 'Prin of Phys Sci' },
    { courseId: 'PHYS 237',creditHours: 3, prefix: 'PHYS', description: 'College Physics I' },
    { courseId: 'PHYS 238',creditHours: 3, prefix: 'PHYS', description: 'College Physics II' },
    { courseId: 'PHYS 251',creditHours: 3, prefix: 'PHYS', description: 'University Physics I' },
    { courseId: 'MUSI 136',creditHours: 3, prefix: 'MUSI', description: 'Music Appreciation' },
    { courseId: 'MUSI 239',creditHours: 3, prefix: 'MUSI', description: 'Fine Arts In Daily Living' },
    { courseId: 'ART 135',creditHours: 3, prefix: 'ART', description: 'Topics in Contemp Art & Culture' },
    { courseId: 'ART 137',creditHours: 3, prefix: 'ART', description: 'Intro African Art' },
    { courseId: 'ART 139',creditHours: 3, prefix: 'ART', description: 'African-American Art & Culture' },
    { courseId: 'THEA 130',creditHours: 3, prefix: 'THEA', description: 'Introduction to Theatre' },
    { courseId: 'ECON 231',creditHours: 3, prefix: 'ECON', description: 'Principles Of Economics I' },
    { courseId: 'ECON 232',creditHours: 3, prefix: 'ECON', description: 'Principles Of Economics II' },
    { courseId: 'HIST 231',creditHours: 3, prefix: 'HIST', description: 'Soc & Pol Hist US to 1877' },
    { courseId: 'HIST 232',creditHours: 3, prefix: 'HIST', description: 'Soc & Pol Hist US Since 1877' },
    { courseId: 'HIST 281',creditHours: 3, prefix: 'HIST', description: 'Intro to African American Hist' },
    { courseId: 'SOC 157',creditHours: 3, prefix: 'SOC', description: 'Introduction To Sociology' },
    { courseId: 'SOC 158',creditHours: 3, prefix: 'SOC', description: 'Contemporary Social Issues' },
    { courseId: 'SOC 221',creditHours: 3, prefix: 'SOC', description: 'Soc Of Human Sexuality' },
    { courseId: 'SOC 238',creditHours: 3, prefix: 'SOC', description: 'Introduction To Anthropology' },
    { courseId: 'SOC 254',creditHours: 3, prefix: 'SOC', description: 'Black Perspec In Soc' },
    { courseId: 'GEOG 132',creditHours: 3, prefix: 'GEOG', description: 'World Regional Geography' },
    { courseId: 'CS 116',creditHours: 3, prefix: 'CS', description: 'Intro To Compr Science I' },
    { courseId: 'EDCI 210',creditHours: 3, prefix: 'EDCI', description: 'Ins Tec' },
    { courseId: 'MATH 132',creditHours: 3, prefix: 'MATH', description: 'Contemporary Mathematics I' },
    { courseId: 'MATH 133',creditHours: 3, prefix: 'MATH', description: 'College Algebra' },
    { courseId: 'MATH 135',creditHours: 3, prefix: 'MATH', description: 'Math and Business and Econ I' },
    { courseId: 'MATH 136',creditHours: 3, prefix: 'MATH', description: 'Precalculus Math' },
    { courseId: 'MIS 204',creditHours: 3, prefix: 'MIS', description: 'Fundamentals of Info Systems' },
    { courseId: 'POLS 235',creditHours: 3, prefix: 'POLS', description: 'American Government' },
    { courseId: 'POLS 236',creditHours: 3, prefix: 'POLS', description: 'Texas Government' },
    { courseId: 'PSY 131',creditHours: 3, prefix: 'PSY', description: 'General Psychology' },
    { courseId: 'SC 135',creditHours: 3, prefix: 'SC', description: 'Bus Prof Comm' },
    { courseId: 'SC 136',creditHours: 3, prefix: 'SC', description: 'Public Address' }
];

export default courses;
